### ISSUE TITLE
First Draft of Mockups for internal review

### ISSUE THREAD

**Issue by erin2722** [MLH-Fellowship/nodemaker#15]
- These will be shown in a meeting internally for initial review

**Comment by erin2722** [comment]
Check out the initial mock-ups [here](https://www.figma.com/proto/sYzEyTfvGB6i26o2ip8kwf/n8n-nodemaker?node-id=23%3A109&scaling=scale-down).

**Comment by ivov** [comment]
Looking good!

- The font and colors fit very well with the n8n style.

- This will be a desktop app, so instead of producing a ZIP file, we'll probably simply output all the various files and directly place them in the `n8n` and `n8n-docs` repos.

- As @ianjennings suggested, it'd be very interesting to have a second section with a mini-IDE containing the output node code, and also allowing for it to be edited on the spot, so that any code edits get reflected back in the input fields of the form.

- If the node has many resources or many operations (very likely), care should be taken to ensure the length of the form does not become overwhelming. Collapsing some form sections might be useful.

- As we discussed, there'd be two types of validation: node parameters and node functionality. I'm not sure if it'd make more sense to validate each resource and operation as they're filled in, or all of them together at the very end.

**Comment by erin2722** [comment]
Thank you for the feedback @ivov! 
I changed the mockups so that instead of outputting to a ZIP file, they output to an IDE which the user can edit and then place into their folders. I think code editing resulting in changing fields is really interesting, but if everyone is ok with it I might implement this first version before jumping into that.
I added an example of form validation and an example of collapsible screens on screen 4.

The updated mockups are on the same link.

**Comment by ivov** [comment]
Agreed! It might be even better to just leave the IDE section at the very end. Having a reactive UI where fields change in a section based on changes to fields in other sections would be super interesting, but I can see how it might become confusing or overwhelming to a first-time user.

Also, perhaps it's because I'm color-blind but I think it'd be useful to have a slightly different color background for a field when it fails validation. I guess it gets a confusing when dark orange is the primary CTA color, and then red signals an invalid input. Maybe it's just me, so perhaps double check with someone else first.

**Comment by erin2722** [comment]
Good point :) just fixed this and made it much redder
