### ISSUE TITLE
env fails on Windows

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/nodemaker#90]
I tried to make my own node for urlbox.io, but this command failed:

I need to use Windows to run electron, but Windows does not have `env`.

```
(node:15916) UnhandledPromiseRejectionWarning: Error: Command failed: env HYGEN_OVERWRITE=1 node node_modules/hygen/dist/bin.js gen generateRegularNodeSimple --name "UrlBox" --metaParameters '{"serviceName":"UrlBox","auth":"Access Token","nodeColor":"","apiURL":"https://api.urlbox.io/v1/"}' --mainParameters '{"Screenshot":[{"name":"Generate","description":"Create a website screenshot","endpoint":"/$$auth_key$$/$$type$$?url=$$url$$","requestMethod":"GET","fields":[{"name":"type","description":"The type of image to generated","type":"string","default":"png"},{"name":"url","description":"The url of the website to screenshot","type":"string","default":"apple.com"}]}]}'
'env' is not recognized as an internal or external command,
operable program or batch file.
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at electron/js2c/asar.js:727:23
    at NodeFilesGenerator.generateMainNodeFile (webpack:///../generators/NodeFilesGenerator.ts?:59:71)
    at NodeFilesGenerator.eval (webpack:///../generators/NodeFilesGenerator.ts?:39:22)
    at step (webpack:///../node_modules/tslib/tslib.es6.js?:124:23)
    at Object.eval [as next] (webpack:///../node_modules/tslib/tslib.es6.js?:105:53)
    at eval (webpack:///../node_modules/tslib/tslib.es6.js?:98:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack:///../node_modules/tslib/tslib.es6.js?:94:12)
(node:15916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

https://www.loom.com/share/ec203ba62ff041c3bb7226f59e52ad50

**Comment by ivov** [comment]
Thanks for your feedback! I've turned it into a [separate issue](https://github.com/MLH-Fellowship/nodemaker/issues/92).

As for this issue, it's likely your combination of params is triggering the error, probably because of your use of the (as of now undocumented and untested) endpoint variable `$$`.

For reference, these are the installation steps:

```sh
git clone https://github.com/MLH-Fellowship/nodemaker.git
npm i
cd client && npm i
cd ..
npm run nodegen
```

If running `nodegen` generated files in `/output`, then the backend works on your Windows box and the problem is in the params. We'd need to see the exact params you're entering in the desktop app, to inspect and debug the object. Sadly, Loom's default video resolution makes the on-screen params illegible. We'll do some tests soon to sort this out.

**Comment by ivov** [comment]
Hi @ianjennings

Much progress has been made since Monday, especially on the setup process and the `$$` route parameter, so it'd be best to try again from scratch. We can open another issue if it persists.
